// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJZXE43-__LaoKVmlaVqKhIFcTwd-HE_o',
    appId: '1:296102513753:web:d36b005013ba4b2339f548',
    messagingSenderId: '296102513753',
    projectId: 'bridge-72b26',
    authDomain: 'bridge-72b26.firebaseapp.com',
    storageBucket: 'bridge-72b26.firebasestorage.app',
    measurementId: 'G-LZ5WLPDM5E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZq5dwaIvKDQ7Tefc81upIv803bXFisSs',
    appId: '1:296102513753:android:4c051d7fec09853a39f548',
    messagingSenderId: '296102513753',
    projectId: 'bridge-72b26',
    storageBucket: 'bridge-72b26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXeVLJj2sLkk4E2a_GA35XYVEzPG0cCFs',
    appId: '1:296102513753:ios:5a96312fa1b4bf9a39f548',
    messagingSenderId: '296102513753',
    projectId: 'bridge-72b26',
    storageBucket: 'bridge-72b26.firebasestorage.app',
    iosBundleId: 'com.example.bridgeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZq5dwaIvKDQ7Tefc81upIv803bXFisSs',
    appId: '1:296102513753:ios:5a96312fa1b4bf9a39f548',
    messagingSenderId: '296102513753',
    projectId: 'bridge-72b26',
    storageBucket: 'bridge-72b26.firebasestorage.app',
    iosBundleId: 'com.example.bridge_app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZq5dwaIvKDQ7Tefc81upIv803bXFisSs',
    appId: '1:296102513753:web:d36b005013ba4b2339f548',
    messagingSenderId: '296102513753',
    projectId: 'bridge-72b26',
    authDomain: 'bridge-72b26.firebaseapp.com',
    storageBucket: 'bridge-72b26.firebasestorage.app',
  );
}